### PR TITLE
fix runnig variable (was not working before)

### LINKED ISSUE #119: Provider ignores "running" parameter for domain
#  Version Reports:

### Distro  version of host:

Ubuntu 14.04

### Terraform Version Report

v0.8.6

### Libvirt version

1.3.1

### terraform-provider-libvirt plugin version (git-hash)

a07e21b74726d9ce443ac9332417c169b2ccd708
___
# Description of Issue/Question
Despite "running = false" domain always running.

### Setup
```
provider "libvirt" {
  uri = "qemu+ssh://root@host/system"
}

resource "libvirt_domain" "rs-removeme" {
  name = "rs-removeme"
  vcpu = 1
  memory = 4096
  running = false
}
```

### Steps to Reproduce Issue
1) Create file with state above
2) terraform apply. [See log](http://paste.openstack.org/show/603763/)

Expected result:
VM is not running

Actual result:
VM is running.

___
# Additional Infos:

No Apparmor

### PR DESCRIPTION
**Pull request by MalloZup**
fix #119

### CODE REVIEW

**Comment by MalloZup** [comment]
@monstermunchkin  feel free to take a look when you have free time.

Thx in advance :jack_o_lantern:

**Comment by MalloZup** [comment]
@monstermunchkin @inercia  feel free to review this. thx

**Comment by dmacvicar** [comment]
Can you help me remember why you named it `domain_shutoff` when the libvirt attribute is called `running` ?

**Comment by MalloZup** [comment]
@dmacvicar  i named it ```domain_shutoff``` because for me was more implicit to use this name. (since we want to shutoff the domain after the creation)
I can change it to  ```running```, if you wish

**Comment by MalloZup** [comment]
@dmacvicar  do you want running as property name? for that no problem.

Or which info do you require? thank you in advance

**Comment by MalloZup** [comment]
@dmacvicar  this pr last time was working, since then i didn't know which info i should you provide.

The history of this pr was:

i saw first https://github.com/dmacvicar/terraform-provider-libvirt/issues/119 issue, and verified, reproduced the bug.

The var 'running ' was not working. 
So we removed it here  with the bless from @monstermunchkin (:rocket: :cupid: :rofl:)
https://github.com/dmacvicar/terraform-provider-libvirt/commit/380076c1943ebd10c5e5f54ad4ac751a736c5c1f

The domain_shutoff name comes from libvirt  jargon,  but i can stick with the `running` name.

**Comment by MalloZup** [comment]
closing in favor of #301

**Pull request closed without merging**
