### PR TITLE
Trivial typo fix

### PR DESCRIPTION
**Pull request by justinclift**

### CODE REVIEW

**Comment by justinclift** [comment]
Hmmm, while looking over the README, shouldn't this:

```
git clone https://github.com/dmacvicar/terraform-provider-libvirt.git
make
```

... also have a `cd` command in there too?  eg:

```
git clone https://github.com/dmacvicar/terraform-provider-libvirt.git
cd terraform-provider-libvirt
make
```

**Comment by MalloZup** [comment]
hi justin thx for pr. Yes you can also put the `cd` on readme thx!

**Review by MalloZup — APPROVED** [review]
thx.

**Comment by justinclift** [comment]
No worries, I've just added that `cd` line too. :smile:

**Pull request merged**
