### PR TITLE
remove duplicata declaration and simplify code.

### PR DESCRIPTION
**Pull request by MalloZup**
This fix is with the cmd "gofmt -w -s *"

### CODE REVIEW

**Comment by dmacvicar** [comment]
Ist that form supported in all Go versions?

**Comment by MalloZup** [comment]
good question, but by default we are building now from only starting from Go 1.8 version, since  Terraform is now primarily targeting Go 1.8. (https://github.com/hashicorp/terraform/issues/12470), and we use the https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/glide.yaml#L7

I tried out the golang 1.9.1 and travis is also using that. 

I can try it out with the lower version the 1.8.

Afai we are implicit removed the support for all go version because of terraform.

**Comment by dmacvicar** [comment]
If it works with 1.8 I am fine with it.

**Comment by MalloZup** [comment]
ok i have pushed a 1.8 golang version on travis. i will remove it

**Comment by MalloZup** [comment]
works with 1.8 https://travis-ci.org/dmacvicar/terraform-provider-libvirt/jobs/303452606

**Comment by MalloZup** [comment]
done . thx all for your review. :city_sunrise: :dog: :dolphin:

**Comment by MalloZup** [comment]
@dmacvicar @monstermunchkin  before merging this, i added a last commit.

https://github.com/dmacvicar/terraform-provider-libvirt/pull/241/commits/c46fb7ff6515ba175728636a98d90d77f14e4f33#diff-2f03be069459ebc91fcf0607d4d686d8R871

https://stackoverflow.com/questions/29164375/golang-correct-way-to-initialize-empty-slice

**Comment by MalloZup** [comment]
imho we can merge this. thx for the time and others suggestions if needed. :mexico: :sunglasses:

**Comment by MalloZup** [comment]
sudo  merge it ( i cannot) 😄

**Pull request merged**
