### PR TITLE
WIP: Fix creating iso for darwin (cloudinit)

### LINKED ISSUE #199: genisoimage is not available on all platforms/distros
genisoimage seems totally unavailable for macOS and doesn't appear to be very common across linux distros

This makes cloudinit isos OS dependent on the client.

I'm going to look for a more common cross platform/distro alternative as this is the only thing that prevents this running anywhere

### PR DESCRIPTION
**Pull request by MalloZup**
fix #199 

- [x] fix with build constraint

- [ ] test the fix #238 contain the test

### CODE REVIEW

**Comment by MalloZup** [comment]
@dmacvicar and @monstermunchkin  i was able to run the test we needed on macosx. :rocket: :rocket: 

```console
=== RUN   TestNewCloudInitDef

--- PASS: TestNewCloudInitDef (0.00s)

=== RUN   TestTerraformKeyOps

--- PASS: TestTerraformKeyOps (0.00s)

=== RUN   TestCreateFiles

2017/11/13 10:27:50 Creating ISO contents

2017/11/13 10:27:50 ISO contents created

--- PASS: TestCreateFiles (0.02s)

=== RUN   TestCreateISONoExteralTool

2017/11/13 10:27:50 Creating new ISO

2017/11/13 10:27:50 Creating ISO contents

2017/11/13 10:27:50 ISO contents created

2017/11/13 10:27:50 About to execute cmd: %+v&{ hdiutil [ hdiutil makehybrid -iso -joliet -o /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/cloudinit085978600 /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/cloudinit085978600/user-data /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/cloudinit085978600/meta-data] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> 0xc42010dc20 false [] [] [] [] <nil> <nil>}

--- PASS: TestCreateISONoExteralTool (0.00s)

=== RUN   TestConvertUserDataToMapPreservesCloudInitNames

--- PASS: TestConvertUserDataToMapPreservesCloudInitNames (0.00s)

```

**Comment by MalloZup** [comment]
@moio  if you have time i would appreciate a tests on your mac, since i have no clue about that mac specific command.

I have already tried with travis, all the basic stuff seems to work.

**Comment by dmacvicar** [comment]
Dario, I think it is better to use build constraints and resolve the right function at compile time and not at runtime (since the ececutables for each OS are not exchangeable):

https://golang.org/pkg/go/build/#hdr-Build_Constraints

This means:

* Rename back `genIsoCmdByOS` to `genIsoCmd`
* Move each version to something like `cloudinit_def.go -> cloudinit_def_linux.go & cloudinit_def_darwin.go` (or as the function can be shared `geniso_linux.go` & `geniso_darwin.go`)

**Comment by MalloZup** [comment]
Ok thx :sunflower

**Comment by MalloZup** [comment]
closing in favor for #249

**Pull request closed without merging**
