### PR TITLE
Fix IPv6 subnet size regression

### PR DESCRIPTION
**Pull request by omertuc**
b0489a5cb128b6acae1976e0383e22bf3d870277 introduced a regression where
the calculation for the number of IPv6 IP addresses always yields a
negative or 0 value, causing users to *always* encounter the following
error when creating IPv6 libvirt networks:

`netmask seems to be too strict: only <0 or negative> IPs available (ipv6)`

(An example is available at the end of [this](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/1883/pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-ipv6/1583020018084352000/artifacts/e2e-metal-assisted-ipv6/assisted-common-test/build-log.txt) CI log)

That commit attempted to fix the wrong use of the `^` operator in the
calculation, which was truely wrong. But it was just wrong in a
relatively "harmless" way, as it wasn't completely blocking users.

The fix in that commit had its own bug - a `1` shifted by `128` always
gives `0`, and not the desired `2 to the power of 128`, because the
latter doesn't fit in a primitive integer type.

To fix this, I've changed the calculation to simply consider the number
of bits available for the subnet, rather than the number of IP addresses
available for the subnet, as that is obviously a much smaller number,
one that the primitive Go integer types can handle

### CODE REVIEW

**Comment by osherdp** [comment]
@dmacvicar just FYI as it's currently a blocker for our usage of the new version v0.7.0

**Comment by dmacvicar** [comment]
Thanks for the patch @omertuc

**Comment by dmacvicar** [comment]
This is included in 0.7.1

**Comment by osherdp** [comment]
Thank you very much!
I'll test it right away

**Pull request merged**
