### PR TITLE
Add cloud-init support for the network-config file.

### PR DESCRIPTION
**Pull request by night199uk**
This allows creating static and custom networking configurations.

Re-opening #270 with documentation added.

### CODE REVIEW

**Comment by night199uk** [comment]
This should be rebased; all tests passing and documentation added. Hopefully this is gtg.

**Comment by dmacvicar** [comment]
My question to the reviewers is if we want to go this path, and starting to add support for all the cloudinit schema.

**Comment by inercia** [comment]
> My question to the reviewers is if we want to go this path, and starting to add support for all the cloudinit schema.

Not sure about this. On one hand, the network configuration seems to be a top-level element of the cloud-init schema, and it is important enough for being managed by the terraform/libvirt provider. On the other hand, this could open a can of worms where we would end up having all the possible cloud-init stuff...

My personal view would be to go for the network configuration, but nothing else.

**Comment by night199uk** [comment]
My understanding is that there are only 3 files that can exist in the ISO?
meta-data
user-data
network-config

I don't think you need to add the entire cloud-init schema. At least allowing folks to place those 3 files avoids having to implement the schema and the user can source those files as they see fit (I use terraform templates).

**Comment by MalloZup** [comment]
I would really like if we improve also the tests coverage for this feature

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/pull/267

**Comment by MalloZup** [comment]
Closing this pr because it will be adressed on https://github.com/dmacvicar/terraform-provider-libvirt/pull/410, were we allow the new field, were the user can add cloud init network data. Thank you for contributing and your time spend on this pr ( reviewer and contributors). Have a nice day

**Pull request closed without merging**
