### PR TITLE
Update to terraform 0.12.0

### LINKED ISSUE #599: Terraform 0.12 update
## Description of Issue
Terraform reached it's [0.12 release](https://github.com/hashicorp/terraform/releases/tag/v0.12.0).  Would be great to make libvirt provider compatible with it.
___
##  System Information

```
./terraform-provider-libvirt f02e17b6216975e343690e34c73f375b5022da92
Compiled against library: libvirt 5.3.0
Using library: libvirt 5.3.0
Running hypervisor: QEMU 4.0.0
Running against daemon: 5.3.0

Terraform v0.12.0
```
___
## Additional information:

At the moment an attempt to run plan fails with API incompatibility error:
```
~/dev/virt> tf plan
Error: Failed to instantiate provider "libvirt" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
```

### PR DESCRIPTION
**Pull request by tripledes**
* Update go.mod to pull terraform v0.12.0
* Update sums accordingly
* Examples split on v0.11 and v0.12 directories
* Use terraform 0.12upgrade to convert examples from old syntax
* Add terraform version requirement for all new examples
* Update terraform version in travis
* Update vendor directory

Tests seem to pass OK and tested a couple of examples after conversion, also worked well.

Should fix #599

### CODE REVIEW

**Comment by MalloZup** [comment]
thx @tripledes for this PR! :+1:  . I will check it once time, stay tuned.

**Comment by MalloZup** [comment]
as open question , I have seen that the `examples` directory and files require tf12. 

This as the side effect that we loose backwards compatibility for people who might want to use a not `12` version.
I'm ok with this, actually.

A way of dealing with multiples examples could be `examples/v012` , `examples/older_v011`, where the second could be historic only. I think it could be kind to  much redundant but I'm asking this if maybe for others could make sense or make more value

**Comment by tripledes** [comment]
@MalloZup agree, it might be too soon to completely get rid of the old-syntax examples, something like `examples/v01[1-2]` maybe? Eventually, the v011 could be removed.

Would you test the 0.11 directory? [Makefile:tf-check](https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/Makefile#L47-L48) If so, I guess travis could get both versions and test both directories.

Happy to make the changes.

**Comment by dmacvicar** [comment]
@MalloZup what do you think that we do a release of the current master, as the last version supporting 0.11.x and then move to support only 0.12 in master (and merge this PR).

But, I like the idea of keeping the examples in separate directories (v0.11.x and v0.12.x).

Lets make a release before merging this one.

**Comment by tripledes** [comment]
@MalloZup @dmacvicar created both directories, `v0.11` and `v0.12`, I haven't changed anything on `.travis.yml` or `Makefile` cause v0.12.0 supports both syntaxes, I haven't seen the need to complicate things.

**Comment by MalloZup** [comment]
@tripledes feel free to solve conflicts :grin:

**Comment by tripledes** [comment]
@MalloZup I'll have some time later today, will have a look and push all the changes.

**Comment by MalloZup** [comment]
to update: 

- So the provider works fine. However I found an issue with the `ubuntu.tf` example, especially the `pool_dir` directory. @tripledes  could you try that example? ( I don't know if it is related to terraform V12. It could be).

Running the testacc cause other failures. This is a breaking change

- resource names with numbers breaks: https://github.com/hashicorp/terraform/issues/19919

And sofar I have seen the Testacc failing for this :/

**Comment by tripledes** [comment]
> Thx so far! looks great.
> 
> I'm testing locally
> 
>     * Minor:
>       a part of the conflicts, I have noticed following:
> 
> 
> 
> ```
> /examples> ls
> count  leap15  ubuntu  v0.11  v0.12
> ```

Sorry, cannot find them on my fork, do you happen to have something in those directories other than what git managed? Like terraform status files and such ?

> 
> the count leap15 ubuntu directory should be removed. ( we need only 2 dirs on the top structure)
> 
>     1. `version.tf` file is superfluous, we should embed it to each file.
> 
> 
> Example:
> 
> `/examples/v0.12/uefi>`
> 
> this directory has currenlty 2 files: `libvirt.tf` and `version.tf`.
> 
> We should remove version and put the content to `libvirt.tf`.
> 
> Having an extra file for version add a complexity and context overloading
> 

Done :+1: 

> If you don't have time currently, i can carry over from your PR and create new one. As you wish!
> thx!

Conflicts were taken care of by git when rebasing.

Regarding the issues you found in the ubuntu example, is this [one](https://github.com/dmacvicar/terraform-provider-libvirt/blob/e6ea88578ee2babfb26f3189c3aa1a6aff96a7ff/examples/v0.12/ubuntu/ubuntu-example.tf) ? I tried this one and besides taking an absurd amount of time, it worked.

**Comment by MalloZup** [comment]
@tripledes thx I will check tomorrow during the day. Thx for effort sofar 💯

**Comment by MalloZup** [comment]
@tripledes yep. So the examples looks good now.

I did a PR for fixing some testacc failure we had. ( https://github.com/dmacvicar/terraform-provider-libvirt/pull/607).

I will merge it soonish. 

Regarding this PR, I need to dive in on the other TestaACC failures to see if we have other failures that need fix.

The problem with go vendor and modules is that it makes PR un-reviewable after :grin: . So dunno, for moment I can push changes to master and we need to rebase here.

If we have kind of not compatible backward changes, we might create a temporary branch where we do PR and we will merge it at the end against master, because otherwise reviewing things when 4000 files change is difficult :grin:

**Comment by MalloZup** [comment]
@dmacvicar  imho we should create a temporary branch called `tf12` or similar where we could merge this PR.  Then we can do smaller fix . I have looked at the test failures and there are some changes needed.  If we do everything here will be rather difficult to review.
e.g we have errors like this
```
--- FAIL: TestAccLibvirtDomain_KernelInitrdCmdline (0.03s)
    testing.go:568: Step 0 error: config is invalid: 2 problems:
        
        - Unsupported block type: Blocks of type "cmdline" are not expected here. Did you mean to define argument "cmdline"? If so, use the equals sign to assign it a value.
        - Unsupported block type: Blocks of type "cmdline" are not expected here. Did you mean to define argument "cmdline"? If so, use the equals sign to assign it a value.
=== RUN   TestAccLibvirtDomain_NetworkInterface
```  

and others types, which need a change of resource schema :/

**Comment by tripledes** [comment]
@MalloZup @dmacvicar the temporary branch makes sense to me, I ran yesterday TestACC and noticed some errors indeed.

Let me know if you go for the temporary branch, happy to try to help :)

**Comment by MalloZup** [comment]
@tripledes I have created a new PR with the branch  https://github.com/dmacvicar/terraform-provider-libvirt/tree/terraform_012, which incorporate you initial commit :+1: 

There is only 1 test Failing. now.  

I"m looking into this test right now. 
```
--- FAIL: TestAccLibvirtDomain_KernelInitrdCmdline (0.01s)
    testing.go:568: Step 0 error: config is invalid: 2 problems:

        - Unsupported block type: Blocks of type "cmdline" are not expected here. Did you mean to define argument "cmdline"? If so, use the equals sign to assign it a value.
        - Unsupported block type: Blocks of type "cmdline" are not expected here. Did you mean to define argument "cmdline"? If so, use the equals sign to assign it a value.
```

We need to adapt the documentation with the new syntax. IF I don't fix the test this afternoon anyone can take over in the rest of weekend or day as you wish. Feel free to send PRs.

**Comment by MalloZup** [comment]
closing as discussed. 

Feel free to send PR to that branch, this will be then Submitted to master when ready. THX a lot for all help! :cupid:

**Pull request closed without merging**
