### PR TITLE
Add link to upstream projects using terraform-kvm

### PR DESCRIPTION
**Pull request by MalloZup**
you can see the markdown here:

https://github.com/MalloZup/terraform-provider-libvirt/tree/doc-showcase#upstream-projects-using-terraform-libvirt

@dmacvicar  for any infos/suggestion changes feel free to ask/add/comment

### CODE REVIEW

**Comment by MalloZup** [comment]
@moio jfyi

**Comment by MalloZup** [comment]
@ereslibre @MaximilianMeister feel free to review the small description i posted about the `kubic` caasp-kvm . if you find a better one i will adapt it TIA :rose: :white_flower:

**Comment by MalloZup** [comment]
@juliogonzalez i added here the description about uyuni, is ok for you?
https://github.com/MalloZup/terraform-provider-libvirt/tree/doc-showcase#upstream-projects-using-terraform-libvirt

**Comment by juliogonzalez** [comment]
@MalloZup it is, but I think you could mention both SUSE Manager and Uyuni (you could link SUSE Manager to https://www.suse.com/products/suse-manager/)

**Comment by MalloZup** [comment]
@juliogonzalez nice ! yop i agree thanks i will add it :love_letter:

**Comment by juliogonzalez** [comment]
@MalloZup and on a second look, better link Uyuni to https://www.uyuni-project.org/ :-)

**Comment by MalloZup** [comment]
@juliogonzalez thx ! both fixed on : https://github.com/MalloZup/terraform-provider-libvirt/tree/doc-showcase#upstream-projects-using-terraform-libvirt

**Comment by MalloZup** [comment]
merging feel free to improve the doc, i added also the small links

**Pull request merged**
