### PR TITLE
WIP: Split DomainCreate function into smaller parts.

### PR DESCRIPTION
**Pull request by MalloZup**
fix partially  #131

### CODE REVIEW

**Comment by MalloZup** [comment]
@inercia @monstermunchkin @flavio do you have something else in mind for refactoring other then this?
https://github.com/dmacvicar/terraform-provider-libvirt/pull/216/files#diff-2f03be069459ebc91fcf0607d4d686d8R169

i was thinking to create an helper variadic function that could take  empty interfaces, with some fixed values for optional true or not, but was kind of overthinking that.

thx in advance :racehorse: :rocket: :robot:

**Comment by flavio** [comment]
I fear @monstermunchkin was working on something similar. Am I wrong?

**Comment by MalloZup** [comment]
@monstermunchkin  if you confirm, ok i will pick up something else thx @flavio

**Comment by monstermunchkin** [comment]
I'm working on this [PR](https://github.com/dmacvicar/terraform-provider-libvirt/pull/193). My approach is also the opposite of what you are doing. IMHO having the `schema.Resource` struct without any helper functions makes it more readable even if the struct is then longer.

**Comment by MalloZup** [comment]
yop @monstermunchkin i am fine then with that. thx for feedback

closing :mobile_phone_off:

**Pull request closed without merging**
