### PR TITLE
FIX Issue#186

### PR DESCRIPTION
**Pull request by rsjethani**

### CODE REVIEW

**Comment by monstermunchkin** [comment]
Please rebase your branch, and apply only the changes that are needed. In this case, just the last commit. Also please use a more descriptive commit title and message.

**Comment by rsjethani** [comment]
hmmm...messed up my commit history....submitting a new one...

**Comment by flavio** [comment]
@rsjethani: please stop closing and creating new PR every time you have to fix something inside of the history.

There are easy ways to [rewrite git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History).

**Comment by rsjethani** [comment]
@flavio sorry about that...won't repeat that.

**Pull request closed without merging**
