### PR TITLE
Automate builds for many linux platforms.

### PR DESCRIPTION
**Pull request by egeneralov**
#### Automate builds for many linux platforms.

You can view build "in-action", get logs and artefacts from [gitlab mirror](https://gitlab.com/egeneralov/terraform-provider-libvirt/pipelines/44024013/builds).

*Please check the opensuse artefacts, I almost did not work with the system.*

### CODE REVIEW

**Comment by dmacvicar** [comment]
Hi @egeneralov 

We already do this for both last release and master branch:

https://build.opensuse.org/package/show/systemsmanagement:terraform/terraform-provider-libvirt
https://build.opensuse.org/package/show/systemsmanagement:terraform:unstable/terraform-provider-libvirt

**Comment by MalloZup** [comment]
Thx, @egeneralov  for pr but as pointed out by @dmacvicar we use already obs. If you think the doc isn't clear feel free to send a pr (thx à lot for this interesting  anyways🎸). Feel free to pick up other issues if you want! Thx

**Comment by dmacvicar** [comment]
If we would be hosted in gitlab it would be very interesting to add it.

May be we could explore using the build automation description with Github actions, and run additional CI here.
I am also interested in exploring how to run the acceptance tests, for which we need nested virtualization.

**Comment by MalloZup** [comment]
@egeneralov thx for pr. Feel free to open an issue if you want to investigate research on being hosted on gitlab, I will close this pr soonish. We can still reference it to a new research issue. Thx

**Comment by MalloZup** [comment]
I am closing this because currently we do t need it. As expressed on commentéd we might investigate on changing host to gitlab if this help with etc. Feel free to open issue for that. Thx for time and passion for that

**Comment by egeneralov** [comment]
Hello.
I created this pr because i realy need more builds for different platforms to run your provider (on debian 9 and ubuntu 16.04).

And my proposition was to have a mirror on gitlab.com for builds and testing. About testing on MR or pushes, i can help you to setup CI for that, but i need some time for research (where to run libvirt more natural on free platforms) and some assistance for write terraform module with good coveredge for your provider, in examples not full coverage, as i see.

P.S.: I not in GitHub Actions beta program, so i can't help with this for now, but i queued my account.

**Comment by MalloZup** [comment]
@egeneralov can you open an issue as follow-up from this PR so we can discuss it there? tia

**Pull request closed without merging**
