### PR TITLE
Added support for importing domain, network, and volume

### PR DESCRIPTION
**Pull request by Pwpon500**
Added Terraform import functionality
Usage:
```
# terraform import libvirt_domain.<name>   <UUID>
# terraform import libvirt_volume.<name>   <path to volume>
# terraform import libvirt_network.<name>   <UUID>
```

### CODE REVIEW

**Comment by MalloZup** [comment]
Ciao @Pwpon500 thx looks good

We need some tests for this, with this helper functions.
https://sourcegraph.com/-/godoc/refs?def=ImportStateCheckFunc&pkg=github.com%2Fhashicorp%2Fterraform%2Fhelper%2Fresource&repo=github.com%2Fhashicorp%2Fterraform

For writing tests check out the contributing guide, there is a link also ( you can also look on other tests for inspiration)

**Comment by MalloZup** [comment]
Are you sure thar we can use the importer by volume path?
https://github.com/hashicorp/terraform/blob/master/helper/schema/resource_importer.go#L49
 Say that we need always an id. Thx ciao

**Comment by Pwpon500** [comment]
OK I'll start writing the tests. You can import based on path because path is how Terraform identifies the libvirt_volume resource. From terraform.tfstate:
```json
"libvirt_volume.vol-debian9-qcow2": {
                    "type": "libvirt_volume",
                    "depends_on": [],
                    "primary": {
                        "id": "/data/drive1/vol-debian9-qcow2",
```
So then the import would something go like this:
`# terraform import libvirt_volume.vol-debian9-qcow2 /data/drive1/vol-debian9-qcow2 `

**Comment by MalloZup** [comment]
Ok cool then! Feel free to ask for any further question

**Comment by Pwpon500** [comment]
How do these tests look @MalloZup?

**Comment by MalloZup** [comment]
@Pwpon500 looks good to me. lgtm. once conflict solved we can merge it from my pov.

@dmacvicar jfy

**Comment by dmacvicar** [comment]
Thanks for the contribution @Pwpon500 . Can you explain a bit what is the current use-case you use this for?

As https://www.terraform.io/docs/import/index.html mentions, there is no generated configuration yet.

```
The current implementation of Terraform import can only import resources into the state. It does not generate configuration. A future version of Terraform will also generate configuration.
```

**Comment by Pwpon500** [comment]
Sure thing. I'm working on writing a program to automatically provision vms (nginx, openvpn, etc.), and I'm using terraform to spin vms up as well as provision existing vms. Import allows me to manage any existing vms/volumes and use existing network resources for the vms. It's also really useful in general for me to be able to manage my existing vms with Terraform.

**Comment by Pwpon500** [comment]
@dmacvicar @MalloZup Is this good to merge? I'm currently using my fork for my systems, and I'd like to be able to switch to the main repo.

**Comment by MalloZup** [comment]
Lgtm for me

**Comment by dmacvicar** [comment]
@Pwpon500 Sorry for the late response. I am having trouble understanding the usefulness of this. I raised a question, regarding the fact that https://www.terraform.io/docs/import/index.html mentions, there is no generated configuration yet.

So, how do you manage existing VMs with this? Can you explain your workflow.

**Comment by Pwpon500** [comment]
I have a bunch of VMs that I created without Terraform, so I can't manage them using Terraform since Terraform isn't currently tracking their states in the .tfstate file. What I want to do is define them in a .tf file and then use the `terraform import` command to import the VMs into my .tfstate file and properly manage them with Terraform. Then I can modify/destroy them using only Terraform.

Does that make sense? If not, I can show an example of one I did recently.

**Comment by inercia** [comment]
@Pwpon500 please rebase your changes (resolving some conflicts). It looks good to me.

**Comment by MalloZup** [comment]
@inercia  i can rebase from @Pwpon500  and i will  then open a PR

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/pull/336

closing in favor for this rebased one

**Pull request closed without merging**
