### PR TITLE
Migrate to terraform-plugin-sdk

### PR DESCRIPTION
**Pull request by LorbusChris**
and update dependencies.

~~Blocked, pending: https://github.com/terraform-providers/terraform-provider-ignition/pull/63
I'll remove the replace directive from go.mod once that PR is in.~~
Unblocked, should be ready to go!

### CODE REVIEW

**Comment by LorbusChris** [comment]
@MalloZup all unblocked, should be ready to go! :)

**Comment by MalloZup** [comment]
@LorbusChris  ok thx! :rocket:  I just need to find a way to review  ` 2,111 ` files . :thinking: :grin:

**Comment by LorbusChris** [comment]
yeah :smile: 
So what I did in the first commit was update the import paths to use `terraform-plugin-sdk` instead of `terraform`, update the go.mod file accordingly, and then run `go mod tidy && go mod vendor`. I.e. all changes in `vendor/` are stem from this. Second commit fixes the tests.

**Comment by LorbusChris** [comment]
I can split out the `vendor/` update (go mod vendor) step into its own commit if that makes it easier for you to review :)

**Comment by MalloZup** [comment]
@LorbusChris yep would help. I will review this in next work days. Thx lot for this effort :rocket:

**Comment by LorbusChris** [comment]
@MalloZup updated :)

**Pull request merged**
