### PR TITLE
Add testify pkg to vendor (missing dependency was needed)

### PR DESCRIPTION
**Pull request by MalloZup**
testify pkg was missing in vendor  i could not develop anymore from master.
fix this
`golang 
libvirt/utils_xslt_test.go:7:2: cannot find package "github.com/stretchr/testify/assert" in any of:
	/home/dmaiocchi/go/src/github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/stretchr/testify/assert (vendor tree)
	/usr/local/go/src/github.com/stretchr/testify/assert (from $GOROOT)
	/home/dmaiocchi/go/src/github.com/stretchr/testify/assert (from $GOPATH)
`

this pr(https://github.com/dmacvicar/terraform-provider-libvirt/pull/431) added testify but without adding the dependence in the vendor/glide pkg mgmt

### CODE REVIEW

**Comment by MalloZup** [comment]
```make testacc``
```
# github.com/dmacvicar/terraform-provider-libvirt/libvirt [github.com/dmacvicar/terraform-provider-libvirt/libvirt.test]
libvirt/provider_test.go:20:3: cannot use ignition.Provider() (type "github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/terraform-providers/terraform-provider-ignition/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider) as type "github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider in map value:
	"github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/terraform-providers/terraform-provider-ignition/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider does not implement "github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider (wrong type for Apply method)
		have Apply(*"github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/terraform-providers/terraform-provider-ignition/vendor/github.com/hashicorp/terraform/terraform".InstanceInfo, *"github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/terraform-providers/terraform-provider-ignition/vendor/github.com/hashicorp/terraform/terraform".InstanceState, *"github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/terraform-providers/terraform-provider-ignition/vendor/github.com/hashicorp/terraform/terraform".InstanceDiff) (*"github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/terraform-providers/terraform-provider-ignition/vendor/github.com/hashicorp/terraform/terraform".InstanceState, error)
		want Apply(*"github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/terraform".InstanceInfo, *"github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/terraform".InstanceState, *"github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/terraform".InstanceDiff) (*"github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/terraform".InstanceState, error)
FAIL	github.com/dmacvicar/terraform-provider-libvirt/libvirt [build failed]
```
I think we had this failure in past but i cannot remember how we fixed it :smile:

**Comment by MalloZup** [comment]
found note on https://github.com/dmacvicar/terraform-provider-libvirt/commit/0ff62a26bf8c4c13df20fec184f2dd787d2dd469 @dmacvicar  feel free to merge this

**Comment by MalloZup** [comment]
@dmacvicar  this is a pkg commit, is good to merge. 
I just runned glige get strip vendor for adding the `assertify` missing dep which was on your GOPATH but not upstream in vendor

**Comment by dmacvicar** [comment]
Included in https://github.com/dmacvicar/terraform-provider-libvirt/pull/487
(sorry, it took me a while to understand all the comments when you mixed the issue with ignition)

**Pull request closed without merging**
