### PR TITLE
Revert "Remove mutex before poolRefresh"

### PR DESCRIPTION
**Pull request by MalloZup**
Reverts dmacvicar/terraform-provider-libvirt#495

fix #https://github.com/dmacvicar/terraform-provider-libvirt/issues/504
I think if we don't find a  solution the wise solution is to revert this.
@wking cc

### CODE REVIEW

**Comment by dmacvicar** [comment]
@wking Do you think you can test this PR and see if that works for you again?

**Comment by wking** [comment]
I can't test now, but should be able to test before tomorrow.  Thanks :)

**Comment by wking** [comment]
Tested with:

```console
$ terraform-provider-libvirt -version
terraform-provider-libvirt 8f4a5f464842b7027e473e3fe4a2671987702cbc
Compiled against library: libvirt 3.9.0
Using library: libvirt 3.9.0
Running hypervisor: QEMU 2.9.0
Running against daemon: 3.9.0
```

and everything works reliably again :).  Thanks again :heart:

**Comment by MalloZup** [comment]
@dmacvicar  imho we can merge this. 

@wking thx for feedback :santa: :mrs_claus: :gift:

**Pull request merged**
