### PR TITLE
FIX waitForLeases invalid key issue

### PR DESCRIPTION
**Pull request by rsjethani**
We are modifying network interface object after adding it as key to
waitForLeases map. This makes the interface object stored in the key
invalid when it is used in functions like hasNetworkAddress() later.

As a result of this the code does not wait for the interface to get
the lease even after specifying `wait_for_lease = true` in the tf
file.

To fix this we move the code to add interface struct object to
waitForLeases map only after all modifications are done i.e. near
to the end of for loop.

For mode details please see [issue#186](https://github.com/dmacvicar/terraform-provider-libvirt/issues/186).

### CODE REVIEW

**Comment by rsjethani** [comment]
@monstermunchkin merged!!!  
I was actually working on adding test cases so as to improve test coverage

**Comment by monstermunchkin** [comment]
@rsjethani sorry, I wasn't aware of that. Feel free to create another PR with the test cases. Increased coverage is always welcome :)

Thanks for your contribution(s) :+1:

**Comment by flavio** [comment]
> I was actually working on adding test cases so as to improve test coverage

@rsjethani: feel free to provide that with another PR ;)

**Comment by rsjethani** [comment]
> @rsjethani sorry, I wasn't aware of that.

@monstermunchkin hey it's fine.

I am actuaaly stuck writing test case for the changes I added. I need to write test case around "wait_for_lease" functionality. I am still going through testing code but so far it seems the iso/volume used for testing gets stuck when tested for "wait_for_lease = true". Should I create a new issue for discussing this problem or some place else. Thanks :)

**Pull request merged**
