### PR TITLE
SCSI use the `sd*` prefix and not the `vd*` prefix

### PR DESCRIPTION
**Pull request by omertuc**
Solves #963

Will write tests once given a green light for this

### CODE REVIEW

**Comment by dmacvicar** [comment]
Thanks for this enhancement.

**Comment by omertuc** [comment]
> Thanks for this enhancement.

Thank you for reviewing & merging this!

Are there any plans for when this will be included in a release?

**Comment by dmacvicar** [comment]
As soon as I manage to get #969 merged.

**Comment by omertuc** [comment]
> As soon as I manage to get #969 merged.

Great, thank you

**Pull request merged**
